# Gitleaks configuration
# - Use default rules
# - Add path allowlists for non-source and legacy areas

[extend]
    useDefault = true

[allowlist]
    description = "allow non-source/legacy and devcontainer scaffolding"
    paths = [
        "^legacy/",
        "^sandbox/",
        "^resources/",
        "^docs/",
        "^api/docs/",
        "^at-includes/",
        "^at-.*\/",
        "^\.devcontainer/",
        "^packages/ui/.*\.(svg|png|jpg|woff2?)$",
        "^apps/web/src/api/schema\.ts$"
    ]


