services:
  api:
    build: ./apps/api
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://tms:tms@db:5432/tms?schema=public
      - JWT_SECRET=dev-secret-change-me
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./apps/api:/app
      - /app/node_modules
  web:
    build: ./apps/web
    command: npm run dev
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./apps/web:/app
      - ./tsconfig.base.json:/tsconfig.base.json:ro
      - /app/node_modules
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=tms
      - POSTGRES_PASSWORD=tms
      - POSTGRES_DB=tms
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db_data:
  minio_data:

