services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    command: node dist/main.js
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://tms:tms@db:5432/tms?schema=public
      - JWT_SECRET=dev-secret-change-me
      - JWT_ISSUER=tms-api
      - JWT_AUDIENCE=tms-web
      - REDIS_URL=redis://redis:6379
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
    ports:
      - "3001:3001"
    depends_on:
      - db
    # No key file mounts needed when using inline JWT_* env vars above
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    command: npm run dev
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - api
    # No host mounts when running compose inside Dev Container
  db:
    image: postgres:16-alpine@sha256:7c688148e5e156d0e86df7ba8ae5a05a2386aaec1e2ad8e6d11bdf10504b1fb7
    environment:
      - POSTGRES_USER=tms
      - POSTGRES_PASSWORD=tms
      - POSTGRES_DB=tms
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine@sha256:bb186d083732f669da90be8b0f975a37812b15e913465bb14d845db72a4e3e08
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  mailpit:
    image: axllent/mailpit:v1.17.1
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db_data:
  minio_data:

# secrets:
#   jwt_private:
#     file: ./apps/api/keys/jwtRS256.key
#   jwt_public:
#     file: ./apps/api/keys/jwtRS256.pub

