name: SBOM

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate SBOM (CycloneDX for npm)
        uses: CycloneDX/gh-node-module-generatebom@v2
        with:
          path: .
          output: sbom-bom.xml
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom-bom.xml

