name: Trivy Container Scan

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build API image
        run: docker build -t tms-api:ci apps/api
      - name: Build Web image
        run: docker build -t tms-web:ci apps/web
      - name: Run Trivy on API image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: tms-api:ci
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
      - name: Run Trivy on Web image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: tms-web:ci
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'

